services:

  ai-engine:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    image: hackathon-ai-engine
    volumes:
      - ollama_storage:/root/.ollama

  webapp:

    build:
      context: .
      dockerfile: Dockerfile
    image: hackathon-webapp
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ai-engine:11434
    volumes:
      - webapp_data:/app/src/data
    depends_on:
      - ai-engine

volumes:
  ollama_storage:
  webapp_data: